#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Invalid usage"
	exit 1
fi
for f in $1; do
	if [ -d $f ]; then
	nrTexts=`ls -al $f | grep -Eic ".*\.txt$"`
	nrFiles=`ls -al $f | grep -Eic ".*"`
	result=`expr $nrTexts / $nrFiles`
	echo "Directorul $f contine $result probabilitate de text"
	fi
done
